/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '04/11/16 11:20' with Gradle 3.1
 *
 * @author luisb, @date 04/11/16 11:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
